RunCPU: Assembler Executor
	@./Assembler.out $(CODE)
	@./Executor.out  $(CODE)

Executor: Executor.cpp TextProcessing.cpp MyStack/Stack.cpp MyStack/Protection.cpp CPU_header.h Commands.h
	@g++ -w Executor.cpp TextProcessing.cpp MyStack/Stack.cpp MyStack/Protection.cpp -o Executor.out

Assembler: Assembler.cpp TextProcessing.cpp CPU_header.h Commands.h
	@g++ -w Assembler.cpp TextProcessing.cpp -o Assembler.out